t1 = time_ns() #tic()
include("test_examples.jl")
include("test_workflow.jl")
include("test_delete_slice_2D.jl")
include("test_delete_slice_3D.jl")
include("filterContinuous_DArray.jl")
include("filterContinuous_SharedArray.jl")
t2 = time_ns() #toc()
println(float(t2-t1)*1e9)
