tic()
include("test_examples.jl")
include("test_workflow.jl")
include("test_delete_slice_2D.jl")
include("test_delete_slice_3D.jl")
include("filterContinuous_DArray.jl")
include("filterContinuous_SharedArray.jl")
toc()
