language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
notifications:
    email: false

sudo: true

matrix:
  allow_failures:
    - julia: nightly

addons:
  apt:
    packages:
      - python3-matplotlib
      - python3-scipy
env:
  matrix:
    - PYTHON=python3 # python 3.5
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes --color=yes -e 'using Pkg; ENV["PYTHON"]=""; Pkg.build("PyCall"); Pkg.add("Conda"); using Conda; Conda.add("scipy"); Pkg.test("BrainWave", coverage=true);'
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("BrainWave")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
- julia -e 'using Pkg; cd(Pkg.dir("BrainWave")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -p 4 --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); ENV["PYTHON"]=""; Pkg.build("PyCall"); using Conda; Conda.add("scipy"); Pkg.build("BrainWave"); Pkg.test("BrainWave"; coverage=true)'
#after_success:
#  - julia -e 'using Pkg; cd(Pkg.dir("BrainWave")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'